server:
  port: 8001
  address: 0.0.0.0   # 监听所有网卡地址
service:
  ipAddr: http://localhost:8001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/training?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  application:
    name: userService8001
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'